# Generated by Django 6.1.1 on 2026-10-07 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='fuelprice',
            constraint=models.UniqueConstraint(fields=('station', 'fuel_type', 'recorded_at'), name='unique_station_fuel_timestamp'),
        ),
    ]
