# Generated by Django 6.1.1 on 2026-10-10 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_fuelprice_unique_station_fuel_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelUpdateConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de actualización',
                'verbose_name_plural': 'Configuración de actualización',
            },
        ),
    ]
